
trigger:
- master

jobs:
  - job: Test
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: Maven@3
      inputs:
        #options: # Optional
        jdkVersionOption: 1.11
    - script: |
          mvn clean verify
      displayName: 'TESTS: backend'
      